### ISSUE TITLE
Does not allow you to configure with Sprint 173 of Azure Devops

### ISSUE THREAD

**Issue by Welchen** [BrandonBoone/npm-audit-widget#29]
Trying to select the Build when setting up the widget in the Dashboard does not work.  The widget keeps saying "N/A not configured"

**Comment by BrandonBoone** [comment]
Was it working prior to https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/sprint-173-update ?

Are you doing anything with the new default branch names feature?

Also, are you publishing the `audit.json` file?

```
  - script: npm audit --json > audit.json
    displayName: 'audit'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: audit_results'
    inputs:
      PathtoPublish: 'audit.json'
      ArtifactName: 'audit_results'
```

On my ADO board the widget is still working, so I'm wondering what the delta might be 🤔.
